all:
	g++ -I/home/sim/raylib/src -o window window.cpp -L/home/sim/raylib -lraylib
	g++ -I/home/sim/raylib/src -o pong pong.cpp -L/home/sim/raylib -lraylib

clean:
	rm -f *.o
	rm -f window
	rm -f pong
